# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

df = pd.read_csv("inflation-consumer.csv")

df.shape

df.head()

df.info()

# change df['Year'] to date format
df['Year'] = pd.to_datetime(df['Year']).dt.year

df.shape

df.sort_values("Inflation")

df.sort_values("Inflation", ascending=False).head(10).plot(kind="bar", x="Country", y="Inflation", title="Top 10 Countries with Highest Inflation")

df.sort_values("Inflation").head(10).plot(kind="bar", x="Country", y="Inflation", title="Top 10 Countries with Highest Deflation")

df.sample(2)

df.groupby("Country")["Year"].count()

df["Year"].value_counts()

df["Country"].value_counts().head(20)

df[df["Country"] == "Nepal"]

df[df["Country"] == "Nepal"].shape[0]

min_inflation = df[df["Country"] == "Nepal"].min()["Inflation"]
max_inflation = df[df["Country"] == "Nepal"].max()["Inflation"]



pd.Series([min_inflation, max_inflation]).plot(kind="bar", title="Nepal's Inflation Range in 1970")

correlation_matrix = df.corr(numeric_only=True)

correlation_matrix

df.info()

# pairplot
sns.pairplot(df)
plt.show()